server:
  port: ${SERVICE_PORT}

user:
  service:
    url: "https://${USER_HOSTNAME}"

eureka:
  instance:
    hostname: ${WEBSITE_HOSTNAME}
    nonSecurePortEnabled: true
    nonSecurePort: 80
    securePortEnabled: false

  client:
    service-url:
      defaultZone: https://${EUREKA_HOSTNAME}/eureka/

spring:
  application:
    name: ms-properties

management:
  endpoints:
    web:
      exposure:
        include: "ping,health"
  health:
    defaults:
      enabled: false    # desactiva chequeos pesados
    ping:
      enabled: true     # responde apenas levante el contexto
    probes:
      enabled: true     # readiness/liveness internos

  # configuracion de la base de datos
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 260MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}

# configuracion de azure
azure:
  blob-storage:
    connection-string: ${AZURE_BLOB_CONNECTION_STRING}
    container-name: images

email:
  username: ${EMAIL_USERNAME}
  password: ${EMAIL_PASSWORD}

frontend:
  base-url: ${SWA_FRONTEND}

client: # Cambiar a Variable de Entorno
  secret: qI8ZfJH8VnL2bBt7T4z0c91wWoTQUxAWm6q1fXKhfH4=

ml:  # Cambiar a Variable de Entorno
  api:
    url: http://localhost:8000

gemini:  # Cambiar a Variable de Entorno
  api:
    key: ${API_KEY_GEMINI}

logging:
  level:
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.orm.jpa: DEBUG

---

# Configuración para perfil "test"
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect