server:
  port: ${SERVICE_PORT}

eureka:
  instance:
    hostname: ${WEBSITE_HOSTNAME}
    nonSecurePortEnabled: true
    nonSecurePort: 80
    securePortEnabled: false

  client:
    service-url:
      defaultZone: https://${EUREKA_HOSTNAME}/eureka/

spring:
  application:
    name: ms-properties

# MOMENTANEO MIENTRAS NO ESTA EL FRONTEND LISTO EN SU PROPIO PIPELINE
  # config:
  #   ignore-unresolvable-placeholders: true

  # configuracion de la base de datos
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  # configuracion del tamaño maximo de archivos
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 260MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOSTNAME}/realms/obertibussoserviciosinmobiliarios

# configuracion de azure
azure:
  blob-storage:
    connection-string: ${AZURE_BLOB_CONNECTION_STRING}
    container-name: images

email:
  username: ${EMAIL_USERNAME}
  password: ${EMAIL_PASSWORD}

frontend:
  base-url: ${SWA_FRONTEND}

---

# Configuración para perfil "test"
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect