spring:
  application:
    name: ms-properties
  # configuracion de la base de datos
  datasource:
    url: jdbc:mysql://localhost:3306/obertibussoserviciosinmobiliarios
    username: root
    password: lmcpauli1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  # configuracion del tamaño maximo de archivos
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 260MB

server:
  port: 8083

# configuracion de azure
azure:
  blob-storage:
    connection-string: BlobEndpoint=https://storageimages.blob.core.windows.net/;SharedAccessSignature=sp=racwdli&st=2025-04-25T01:30:08Z&se=2030-04-28T09:30:08Z&spr=https&sv=2024-11-04&sr=c&sig=lV0U9sQjS0hYfhyr0mUB83ERerAqkLMloPnYpkdVzXc%3D
    container-name: images

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka