name: CI/CD - MS Users

on:
  workflow_dispatch:
  push:
    branches:
      - feature/pipelines
  # - main

permissions:
  contents: read
  checks: write
# --------------------------------------------------------------
# VARIABLES GLOBALES
# --------------------------------------------------------------
env:
  # Azure
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

  # Docker Hub
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  # Properties-specific
  IMAGE_NAME: ms-users
  APP_PLAN_DEV: ${{ secrets.APP_PLAN_DEV }}
  APP_PLAN_PROD: ${{ secrets.APP_PLAN_PROD }}
  APP_NAME_DEV: ${{ secrets.APP_USERS_DEV }}
  APP_NAME_PROD: ${{ secrets.APP_USERS_PROD }}
  SERVICE_PORT: 8081

  # Utils
  SPRING_DATASOURCE_URL_DEV: ${{ secrets.DB_SQL_URL_DEV }}
  SPRING_DATASOURCE_URL_PROD: ${{ secrets.DB_SQL_URL_PROD }}
  SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_SQL_USERNAME }}
  SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_SQL_PASSWORD }}

  EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  # FRONTEND_BASE_URL:

jobs:
  # --------------------------------------------------------------
  # JOB 1: Build · Test · Docker
  # --------------------------------------------------------------
  build-and-push:
    name: Build · Test · Docker
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "24"

      # - name: Run Unit Tests
      #   working-directory: backend/${{ env.IMAGE_NAME }}
      #   run: mvn -B clean test jacoco:report -Dmaven.test.failure.ignore=false

      # - name: Publish JUnit Results
      #   uses: EnricoMi/publish-unit-test-result-action@v2
      #   if: always()
      #   with:
      #     files: backend/${{ env.IMAGE_NAME }}/target/surefire-reports/*.xml

      # - name: Test Summary
      #   uses: test-summary/action@v2
      #   if: always()
      #   with:
      #     paths: backend/${{ env.IMAGE_NAME }}/target/surefire-reports/*.xml

      # - name: Publish JaCoCo Coverage
      #   id: jacoco
      #   uses: PavanMudigonda/jacoco-reporter@v5.0
      #   with:
      #     coverage_results_path: backend/${{ env.IMAGE_NAME }}/target/site/jacoco/jacoco.xml
      #     coverage_report_name: Code Coverage
      #     coverage_report_title: "JaCoCo Coverage"
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     minimum_coverage: 80
      #     publish_only_summary: false

      - name: Build & Package JAR
        working-directory: backend/${{ env.IMAGE_NAME }}
        run: mvn -B package -DskipTests

      - name: Upload Backend JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}-jar
          path: backend/${{ env.IMAGE_NAME }}/target/*.jar

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set Docker image tag
        id: set-tag
        run: |
          TAG=${GITHUB_SHA::8}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build & Push Docker image
        run: |
          TAG=${{ steps.set-tag.outputs.tag }}
          IMAGE="docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:$TAG"
          docker build -t $IMAGE -f backend/${{ env.IMAGE_NAME }}/Dockerfile backend/${{ env.IMAGE_NAME }}
          docker push $IMAGE

  # --------------------------------------------------------------
  # JOB 2: Deploy to Development
  # --------------------------------------------------------------
  deploy-dev:
    name: Deploy to Development
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Set variables
        id: vars
        run: |
          echo "IMAGE=docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.build-and-push.outputs.tag }}" >> $GITHUB_ENV

      - name: Create Web App (if not exists)
        run: |
          az webapp create \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --plan ${{ env.APP_PLAN_DEV }} \
            --name ${{ env.APP_NAME_DEV }} \
            --deployment-container-image-name $IMAGE || true

      - name: Configure Web App container
        run: |
          az webapp config container set \
            --name ${{ env.APP_NAME_DEV }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --container-image-name $IMAGE \
            --container-registry-url https://index.docker.io \
            --container-registry-user ${{ env.DOCKERHUB_USERNAME }} \
            --container-registry-password ${{ env.DOCKERHUB_TOKEN }}

      - name: Ensure App Service Is Running
        run: |
          echo "Verificando estado del App Service..."
          status=$(az webapp show \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ env.APP_NAME_DEV }} \
            --query state -o tsv)
          echo "Estado actual: $status"
          if [ "$status" != "Running" ]; then
            echo "🔄 Iniciando App Service..."
            az webapp start \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --name ${{ env.APP_NAME_DEV }}
          else
            echo "✅ App Service ya está en ejecución."
          fi

      - name: Fetch FQDNs
        run: |
          FRONTEND_FQDN=$(az staticwebapp show \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.SWA_FRONTEND_DEV }} \
            --query defaultHostname -o tsv)
          echo "🔖 Frontend FQDN: $FRONTEND_FQDN"
          echo "FRONTEND_HOSTNAME=$FRONTEND_FQDN" >> $GITHUB_ENV

      - name: Set environment variables (App Settings)
        run: |
          az webapp config appsettings set \
            --name ${{ env.APP_NAME_DEV }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --settings \
              "SERVICE_PORT=${{ env.SERVICE_PORT }}" \
              "WEBSITES_PORT=${{ env.SERVICE_PORT }}" \
              "EUREKA_HOSTNAME=${{ secrets.APP_EUREKA_DEV }}.azurewebsites.net" \
              "APP_HOSTNAME=$WEBSITE_HOSTNAME" \
              "KEYCLOAK_HOSTNAME=${{ secrets.APP_KEYCLOAK_DEV }}.azurewebsites.net" \
              "SPRING_DATASOURCE_URL=${{ env.SPRING_DATASOURCE_URL_DEV }}" \
              "SPRING_DATASOURCE_USERNAME=${{ env.SPRING_DATASOURCE_USERNAME }}" \
              "SPRING_DATASOURCE_PASSWORD=${{ env.SPRING_DATASOURCE_PASSWORD }}" \
              "EMAIL_USERNAME=${{ env.EMAIL_USERNAME }}" \
              "EMAIL_PASSWORD=${{ env.EMAIL_PASSWORD }}" \
              "KEYCLOAK_SB_CLIENT_ID=${{ secrets.KEYCLOAK_SB_CLIENT_ID }}" \
              "KEYCLOAK_SB_CLIENT_SECRET=${{ secrets.KEYCLOAK_SB_CLIENT_SECRET_DEV }}" \
              "SWA_FRONTEND=$FRONTEND_HOSTNAME" \
              "PROPERTY_HOSTNAME=${{ secrets.APP_PROPERTIES_DEV }}.azurewebsites.net"

      - name: Restart Web App to apply App Settings
        run: |
          az webapp restart \
          --name ${{ env.APP_NAME_DEV }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }}

      - name: Enable Container Logs
        run: |
          az webapp log config \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ env.APP_NAME_DEV }} \
            --docker-container-logging filesystem

  # --------------------------------------------------------------
  # JOB 3: Deploy to Production
  # --------------------------------------------------------------
  deploy-prod:
    name: Deploy to Production
    needs: [deploy-dev, build-and-push]
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Set variables
        id: vars
        run: |
          echo "IMAGE=docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.build-and-push.outputs.tag }}" >> $GITHUB_ENV

      - name: Create Web App (if not exists)
        run: |
          az webapp create \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --plan ${{ env.APP_PLAN_PROD }} \
            --name ${{ env.APP_NAME_PROD }} \
            --deployment-container-image-name $IMAGE || true

      - name: Configure Web App container
        run: |
          az webapp config container set \
            --name ${{ env.APP_NAME_PROD }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --container-image-name $IMAGE \
            --container-registry-url https://index.docker.io \
            --container-registry-user ${{ env.DOCKERHUB_USERNAME }} \
            --container-registry-password ${{ env.DOCKERHUB_TOKEN }}

      - name: Ensure App Service Is Running
        run: |
          echo "Verificando estado del App Service..."
          status=$(az webapp show \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ env.APP_NAME_PROD }} \
            --query state -o tsv)
          echo "Estado actual: $status"
          if [ "$status" != "Running" ]; then
            echo "🔄 Iniciando App Service..."
            az webapp start \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --name ${{ env.APP_NAME_PROD }}
          else
            echo "✅ App Service ya está en ejecución."
          fi

      - name: Fetch FQDNs
        run: |
          FRONTEND_FQDN=$(az staticwebapp show \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.SWA_FRONTEND_PROD }} \
            --query defaultHostname -o tsv)
          echo "🔖 Frontend FQDN: $FRONTEND_FQDN"
          echo "FRONTEND_HOSTNAME=$FRONTEND_FQDN" >> $GITHUB_ENV

      - name: Set environment variables (App Settings)
        run: |
          az webapp config appsettings set \
            --name ${{ env.APP_NAME_PROD }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --settings \
              "SERVICE_PORT=${{ env.SERVICE_PORT }}" \
              "WEBSITES_PORT=${{ env.SERVICE_PORT }}" \
              "EUREKA_HOSTNAME=${{ secrets.APP_EUREKA_PROD }}.azurewebsites.net" \
              "APP_HOSTNAME=$WEBSITE_HOSTNAME" \
              "KEYCLOAK_HOSTNAME=${{ secrets.APP_KEYCLOAK_PROD }}.azurewebsites.net" \
              "SPRING_DATASOURCE_URL=${{ env.SPRING_DATASOURCE_URL_PROD }}" \
              "SPRING_DATASOURCE_USERNAME=${{ env.SPRING_DATASOURCE_USERNAME }}" \
              "SPRING_DATASOURCE_PASSWORD=${{ env.SPRING_DATASOURCE_PASSWORD }}" \
              "EMAIL_USERNAME=${{ env.EMAIL_USERNAME }}" \
              "EMAIL_PASSWORD=${{ env.EMAIL_PASSWORD }}" \
              "KEYCLOAK_SB_CLIENT_ID=${{ secrets.KEYCLOAK_SB_CLIENT_ID }}" \
              "KEYCLOAK_SB_CLIENT_SECRET=${{ secrets.KEYCLOAK_SB_CLIENT_SECRET_PROD }}" \
              "SWA_FRONTEND=$FRONTEND_HOSTNAME" \
              "PROPERTY_HOSTNAME=${{ secrets.APP_PROPERTIES_PROD }}.azurewebsites.net"

      - name: Restart Web App to apply App Settings
        run: |
          az webapp restart \
          --name ${{ env.APP_NAME_PROD }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }}

      - name: Enable Container Logs
        run: |
          az webapp log config \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ env.APP_NAME_PROD }} \
            --docker-container-logging filesystem
