name: CI/CD - Eureka Server

on:
  push:
    branches: [feature/pipeline]
  workflow_dispatch:

# ────────────────────────────────────────────────────────────────────────────────
# 1) ENVIRONS GLOBALES (resueltos antes de ejecutar cualquier step)
# ────────────────────────────────────────────────────────────────────────────────
env:
  # Azure
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  ACA_ENVIRONMENT: ${{ secrets.ACA_ENVIRONMENT }}

  # Docker Hub
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  # Health check
  HEALTH_PATH: /actuator/health
  HEALTH_TIMEOUT: 60

  # Eureka-specific
  IMAGE_NAME: eureka-server
  CONTAINERAPP_NAME: aca-eureka-server
  SERVICE_PORT: 8761

jobs:
  # ────────────────────────────────────────────────────────────────────────────────
  # JOB 1: Build · Test · Coverage · Docker
  # ────────────────────────────────────────────────────────────────────────────────
  build-and-push:
    runs-on: ubuntu-latest
    environment: development

    outputs:
      tag: ${{ steps.build-image.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "24"

      # - name: Run Backend Tests
      #   working-directory: backend/${{ env.IMAGE_NAME }}
      #   run: mvn -B test

      # - uses: EnricoMi/publish-unit-test-result-action@v2
      #   if: always()
      #   with:
      #     files: backend/${{ env.IMAGE_NAME }}/target/surefire-reports/*.xml

      # - uses: test-summary/action@v2
      #   if: always()
      #   with:
      #     paths: backend/${{ env.IMAGE_NAME }}/target/surefire-reports/*.xml

      # - uses: PavanMudigonda/jacoco-reporter@v5.0
      #   with:
      #     coverage_results_path: backend/${{ env.IMAGE_NAME }}/target/site/jacoco/jacoco.xml
      #     coverage_report_name: Code Coverage
      #     coverage_report_title: "📈 JaCoCo Coverage"
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     minimum_coverage: 80
      #     publish_only_summary: true

      - name: Build & Package JAR
        working-directory: backend/${{ env.IMAGE_NAME }}
        run: mvn -B package -DskipTests

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}-jar
          path: backend/${{ env.IMAGE_NAME }}/target/*.jar

      - uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - id: build-image
        run: |
          TAG=${GITHUB_SHA::8}
          IMAGE="docker.io/${DOCKERHUB_USERNAME}/${IMAGE_NAME}:$TAG"
          docker build -t $IMAGE -f backend/${IMAGE_NAME}/Dockerfile backend/${IMAGE_NAME}
          docker push $IMAGE
          echo "tag=$TAG" >> $GITHUB_OUTPUT

  # ────────────────────────────────────────────────────────────────────────────────
  # JOB 2: Deploy to Development
  # ────────────────────────────────────────────────────────────────────────────────
  deploy-dev:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Deploy Eureka Container App
        uses: azure/cli@v1
        with:
          azcliversion: latest
          inlineScript: |
            set -e
            # 1) Resuelvo aquí el output del job anterior
            TAG=${{ needs.build-and-push.outputs.tag }}
            IMAGE="docker.io/${DOCKERHUB_USERNAME}/${IMAGE_NAME}:$TAG"

            # 2) Crear si no existe
            if ! az containerapp show -g $AZURE_RESOURCE_GROUP -n $CONTAINERAPP_NAME &>/dev/null; then
              az containerapp create \
                -g $AZURE_RESOURCE_GROUP -n $CONTAINERAPP_NAME \
                --environment $ACA_ENVIRONMENT \
                --image $IMAGE \
                --ingress external \
                --target-port $SERVICE_PORT \
                --registry-server docker.io \
                --registry-username $DOCKERHUB_USERNAME \
                --registry-password $DOCKERHUB_TOKEN \
                --cpu 0.25 \
                --memory 0.5Gi
            fi

            # 3) Forzar mínimo 1 réplica + actualizar imagen y env-var
            FQDN=$(az containerapp show \
                     -g $AZURE_RESOURCE_GROUP -n $CONTAINERAPP_NAME \
                     --query properties.configuration.ingress.fqdn -o tsv)
            echo "EUREKA_FQDN=$FQDN" >> $GITHUB_ENV
            az containerapp update \
              -g $AZURE_RESOURCE_GROUP -n $CONTAINERAPP_NAME \
              --image $IMAGE \
              --min-replicas 1 \
              --set-env-vars EUREKA_HOSTNAME=$FQDN

      - name: Health check con reintentos
        run: |
          URL="https://$EUREKA_FQDN${{ env.HEALTH_PATH }}"
          for i in $(seq 1 10); do
            HTTP=$(curl -s -o /dev/null -w "%{http_code}" $URL) || true
            if [[ "$HTTP" -ge 200 && "$HTTP" -lt 300 ]]; then
              echo "✅ Healthy (status $HTTP)"; exit 0
            fi
            sleep 10
          done
          echo "❌ Health check failed"; exit 1
